### ISSUE TITLE
Numbered lines

### ISSUE THREAD

**Issue by chrfs** [webdevnerdstuff/vue3-code-block#23]
Hello,

I would to ask if numbered lined are planned or if I can add a PR with the feature.

Best regards

**Comment by webdevnerdstuff** [comment]
This component is more of a wrapper for PrismJS and Highlight.js, so the line numbering is more of a feature of those plugins. Prism does have a [line numbers plugin](https://prismjs.com/plugins/line-numbers/) that does work with the Vue3 CodeBlock component (example on the site), Highlight.js [does not have line numbers](https://highlightjs.readthedocs.io/en/latest/line-numbers.html) available.

There is no plan to add line numbers to the Vue3 CodeBlock component, and I'd be hesitant to add it due to it's integration using two external libraries.
